theme: jekyll-theme-minimal
title: BEAP'20
name: First International Workshop on Business and Enterprise Architecture in Practice
description: <a href="https://www.uantwerpen.be/en/conferences/business-informatics/" target="_blank">22nd IEEE International Conference on Business Informatics, IEEE CBI 2020</a> in Antwerp June 22-24, 2020.
logo: /assets/img/profile.jpeg
twitter_username: beap_ws
email: blagovesta.pirelli at epfl.ch
future: true
