theme: jekyll-theme-minimal
acronym: BEAP'20
full_name: First International Workshop on Business and Enterprise Architecture in Practice
description: Co-located with CBI'20
logo: /assets/img/profile.jpeg
twitter_username: beap_ws
email: blagovesta.pirelli at epfl.ch
future: true
baseurl: /docs
